#!/usr/bin/env python3
"""Launch an AI assistant in a Docker container.

This module provides a command-line interface equivalent to the previous
ai-assistant.sh script. It handles optional Docker image builds, container
cleanup, and running the assistant in a Docker container with workspace
isolation, audio support, and Docker-outside-of-Docker capabilities.

When installed as part of the `.agent` directory, this script keeps all
helper files, the Docker build context, and all caches inside `.agent`,
while the project root is bind-mounted into the container at the identical
path and used as the container working directory. Two invariants follow
from this design:

1. Aider can read and edit application source code anywhere under the
   project root, because the root is mounted at the same path it has on
   the host.
2. `docker` / `docker compose` commands run from inside the container
   operate on the host daemon via the mounted docker.sock, and any
   bind-mount paths in compose files resolve correctly because the project
   root path is identical inside and outside the container.
"""

from __future__ import annotations

import hashlib
import os
import re
import signal
import subprocess
import sys
import tempfile
import time
from collections import deque
from pathlib import Path
from typing import Optional

TOOL_NAME = "ai-assistant"
AIDER_IMAGE = "aider-agent:latest"
BASE_IMAGE_FALLBACK = "paulgauthier/aider-full:latest"
SESSION_ID_ENV_VAR = "AI_ASSISTANT_SESSION_ID"

ANSI_RED = "\033[31m"
ANSI_GREEN = "\033[32m"
ANSI_RESET = "\033[0m"
SPIN_CHARS = ["-", "\\", "|", "/", "."]

LOG_RE = re.compile(
    r"(?:RUN|COPY|FROM|Installing|Extracting|Downloading|Unpacking|"
    r"Setting up|Get:|added|CACHED|ERROR|error).*"
)

AGENT_DIR = Path(__file__).resolve().parent

DOCKERIGNORE_CONTENT = """\
# Auto-generated by ai_assistant.py.
# The Dockerfile performs no COPY instructions, so the build context is kept
# minimal (just the Dockerfile) to make builds fast on large projects.
# If you add COPY instructions, whitelist the required files below.
*
!Dockerfile.aider
"""


def _remove_if_empty(path: Path) -> None:
    """Remove a directory if it exists and is empty."""
    try:
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    except OSError:
        pass


def _docker_available(debug: bool = False) -> bool:
    """Return True when the docker CLI can be executed."""
    command = ["docker", "version"]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _trace_command(command: list[str], debug: bool) -> None:
    """Print a command to stderr when debug output is enabled."""
    if debug:
        print("+", " ".join(command), file=sys.stderr)


def _tail_lines(path: Path, count: int) -> list[str]:
    """Return up to the last count lines from a text file."""
    try:
        lines = path.read_text(errors="replace").splitlines()
    except FileNotFoundError:
        return []
    return lines[-count:] if count > 0 else lines


def _print_spinner_update(char: str, message: str) -> None:
    """Print a single-line spinner status update when stdout is a TTY."""
    if not sys.stdout.isatty():
        return
    sys.stdout.write(f"\r[{char}] Loading AI Assistant... {message:<50}")
    sys.stdout.flush()


def _get_docker_gid() -> Optional[int]:
    """Return the Docker group GID, or None when the group is unavailable."""
    try:
        import grp
        return grp.getgrnam("docker").gr_gid
    except (KeyError, ImportError):
        return None


def _aider_config_args(agent_dir: Path) -> list[str]:
    """Return Aider CLI flags for config files stored in agent_dir."""
    args: list[str] = []

    config_file = agent_dir / ".aider.conf.yml"
    if config_file.exists():
        args.extend(["--config", str(config_file)])

    model_settings_file = agent_dir / ".aider.model.settings.yml"
    if model_settings_file.exists():
        args.extend(["--model-settings-file", str(model_settings_file)])

    aiderignore_file = agent_dir / ".aiderignore"
    if aiderignore_file.exists():
        args.extend(["--aiderignore", str(aiderignore_file)])

    model_metadata_file = agent_dir / ".aider.model.metadata.json"
    if model_metadata_file.exists():
        args.extend(["--model-metadata-file", str(model_metadata_file)])

    return args


def _base_repo_digests(image: str, debug: bool = False) -> str:
    """Return local repo digests for an image, or "" when unknown."""
    command = [
        "docker",
        "image",
        "inspect",
        "--format",
        "{{range .RepoDigests}}{{.}} {{end}}",
        image,
    ]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return ""
    if result.returncode != 0:
        return ""
    return (result.stdout or "").strip()


def _base_image(dockerfile_path: Path) -> str:
    """Extract the FROM image reference from a Dockerfile."""
    try:
        for line in dockerfile_path.read_text(errors="replace").splitlines():
            stripped = line.strip()
            if stripped.upper().startswith("FROM"):
                for token in stripped.split()[1:]:
                    if not token.startswith("--"):
                        return token
    except OSError:
        pass
    return BASE_IMAGE_FALLBACK


def _image_cache_tag(dockerfile_path: Path, debug: bool = False) -> str:
    """Return a content-hash tag for the built image.

    Combines the Dockerfile bytes with the base image's repo digests, so the
    cache tag changes (triggering a rebuild) whenever either the Dockerfile
    or the upstream base image changes. Before the first local pull the base
    contributes "" to the hash; after a successful build the tag is
    recomputed and refreshed (see main()).
    """
    hasher = hashlib.sha256()
    try:
        hasher.update(dockerfile_path.read_bytes())
    except OSError:
        pass
    hasher.update(_base_repo_digests(_base_image(dockerfile_path), debug).encode())
    return f"aider-agent:c-{hasher.hexdigest()[:16]}"


def _image_exists(tag: str, debug: bool = False) -> bool:
    """Return True when a local Docker image exists for the given tag."""
    command = ["docker", "image", "inspect", tag]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _ensure_build_dockerignore(agent_dir: Path) -> None:
    """Create a minimal .dockerignore in agent_dir when one is missing."""
    target = agent_dir / ".dockerignore"
    if target.exists():
        return
    try:
        target.write_text(DOCKERIGNORE_CONTENT)
    except OSError:
        pass


def _warn_agent_dir_location(project_root: Path) -> None:
    """Warn when .agent is not inside the project root.

    The container bind-mounts the project root at the same path. Aider config
    and history paths (which live in .agent) only resolve inside the container
    when .agent is a subdirectory of the project root.
    """
    try:
        AGENT_DIR.relative_to(project_root)
    except ValueError:
        print(
            "Warning: the .agent directory is outside the project root; "
            "aider config and history files may not be visible inside the "
            "container.",
            file=sys.stderr,
        )


def _resolve_session_id() -> str:
    """Return the session identifier used for container naming and labels.

    Resolution order:
    1. The AI_ASSISTANT_SESSION_ID environment override, so any editor or
       shell can group multiple terminals into a single session.
    2. The tmux session identity (TMUX is shared by all panes of a session).
    3. The GNU screen session name (STY).
    4. The parent shell PID, giving each plain terminal its own session.

    Returns:
        A session identifier restricted to Docker's legal container-name
        characters, because the value is embedded in the container name.
    """
    override = os.environ.get(SESSION_ID_ENV_VAR)
    if override:
        raw = override
    elif os.environ.get("TMUX"):
        # TMUX holds "<socket>,<server-pid>,<session>,..." and is shared by
        # every pane attached to the same tmux session.
        raw = "tmux-" + os.environ["TMUX"]
    elif os.environ.get("STY"):
        raw = "screen-" + os.environ["STY"]
    else:
        raw = str(os.getppid())
    return re.sub(r"[^a-zA-Z0-9_.-]", "_", raw)


def _pid_alive(pid_text: str) -> bool:
    """Return True when the given host PID currently exists."""
    try:
        pid = int(pid_text)
    except (TypeError, ValueError):
        return False
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


def _remove_container(container_ref: str, debug: bool = False) -> None:
    """Force-remove a container by name or ID. Missing containers are ignored."""
    command = ["docker", "rm", "-f", container_ref]
    try:
        _trace_command(command, debug)
        subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        pass


def _set_parent_death_signal(sig: int) -> None:
    """Ask the kernel to signal this process when its parent dies."""
    try:
        import ctypes

        libc = ctypes.CDLL("libc.so.6", use_errno=True)
        pr_set_pdeathsig = 1
        libc.prctl.argtypes = [ctypes.c_int, ctypes.c_ulong]
        libc.prctl.restype = ctypes.c_int
        libc.prctl(pr_set_pdeathsig, sig)
    except (OSError, AttributeError):
        pass


def _start_container_watchdog(container_name: str, debug: bool = False) -> int:
    """Fork a child that removes the container if this process dies.

    Uses PR_SET_PDEATHSIG so SIGKILL of the launcher still stops the
    container, and polls getppid() as a fallback when prctl is unavailable.
    """
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        pid = os.fork()
    except OSError:
        return -1
    if pid > 0:
        return pid

    try:
        os.setsid()
    except OSError:
        try:
            os.setpgrp()
        except OSError:
            pass

    signal.signal(signal.SIGINT, signal.SIG_IGN)
    signal.signal(signal.SIGHUP, signal.SIG_IGN)
    parent = os.getppid()
    _set_parent_death_signal(signal.SIGTERM)

    def _cleanup(_signum=None, _frame=None):
        _remove_container(container_name, debug)
        os._exit(0)

    signal.signal(signal.SIGTERM, _cleanup)
    if os.getppid() != parent or os.getppid() == 1:
        _cleanup()
    while True:
        time.sleep(1)
        if os.getppid() != parent or os.getppid() == 1:
            _cleanup()


def _stop_watchdog(watchdog_pid: int) -> None:
    """Terminate a watchdog child started by _start_container_watchdog."""
    if watchdog_pid <= 0:
        return
    try:
        os.kill(watchdog_pid, signal.SIGKILL)
    except OSError:
        pass
    try:
        os.waitpid(watchdog_pid, 0)
    except OSError:
        pass


def _running_in_container() -> bool:
    """Return True when this launcher is itself running inside a container.

    Docker creates /.dockerenv in every container it starts, so the file's
    presence is a reliable marker for a nested launcher invocation. From
    inside a container the host PID space is invisible, so stale-container
    cleanup must not run (see cleanup_containers).
    """
    return Path("/.dockerenv").exists()


def cleanup_containers(
    workspace_hash: str,
    debug: bool = False,
) -> None:
    """Remove leftover containers whose host launcher process is not alive.

    Live launchers in the same workspace are left running so multiple
    terminals can coexist. Session identity is not used for cleanup.

    Arguments:
        workspace_hash: Aider directory hash used as a Docker label.
        debug: Whether to print the underlying Docker commands to stderr.

    Returns:
        None
    """
    command = [
        "docker",
        "ps",
        "-a",
        "--filter",
        f"label=aider.dir={workspace_hash}",
        "--format",
        '{{.ID}} {{.Label "aider.hostpid"}}',
    ]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        print("Warning: unable to locate the Docker CLI.", file=sys.stderr)
        return

    if result.returncode != 0:
        warning = (result.stderr or "").strip()
        if warning:
            print(f"Warning: unable to list Docker containers: {warning}", file=sys.stderr)
        else:
            print(
                f"Warning: docker ps exited with status {result.returncode}.",
                file=sys.stderr,
            )
        return

    stale_ids = []
    for line in (result.stdout or "").splitlines():
        fields = line.split()
        if not fields:
            continue
        # Unlabeled leftovers (no hostpid) are treated as orphaned.
        host_pid = fields[1] if len(fields) > 1 else ""
        if not _pid_alive(host_pid):
            stale_ids.append(fields[0])
    for container_id in stale_ids:
        _remove_container(container_id, debug=debug)


def build_image(
    dockerfile_path: Path,
    context_dir: Path,
    debug: bool = False,
) -> int:
    """Build the Docker image with a progressive status indicator.

    Arguments:
        dockerfile_path: Path to the project Dockerfile.
        context_dir: Docker build context directory. The Dockerfile contains
            no COPY instructions, so a minimal context (the .agent directory)
            keeps builds fast even for very large projects.
        debug: Whether to print the underlying Docker command to stderr.

    Returns:
        0 on success, otherwise the Docker build exit code.
    """
    log_handle = tempfile.NamedTemporaryFile(
        mode="w",
        prefix="ai-assistant-build-",
        suffix=".log",
        delete=False,
    )
    log_path = Path(log_handle.name)
    log_handle.close()

    try:
        command = [
            "docker",
            "build",
            "--progress=plain",
            "-t",
            AIDER_IMAGE,
            "-f",
            str(dockerfile_path),
            str(context_dir),
        ]
        _trace_command(command, debug)

        env = os.environ.copy()
        env["DOCKER_BUILDKIT"] = "1"

        with log_path.open("w") as log_file:
            try:
                process = subprocess.Popen(
                    command,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                    env=env,
                )
            except FileNotFoundError:
                print(
                    f"{ANSI_RED}Docker CLI not found while building image.{ANSI_RESET}",
                    file=sys.stderr,
                )
                return 127

            # Incremental log tail: read only newly appended bytes each tick
            # instead of re-reading and re-scanning the whole log file.
            spin_index = 0
            tail: deque[str] = deque(maxlen=40)
            reader = None
            try:
                reader = log_path.open("rb")
            except OSError:
                reader = None

            while process.poll() is None:
                if reader is not None:
                    chunk = reader.read()
                    if chunk:
                        tail.extend(
                            chunk.decode("utf-8", errors="replace").splitlines()
                        )

                status_message = ""
                if tail:
                    status_message = next(
                        (line for line in reversed(tail) if LOG_RE.search(line)),
                        "",
                    )[:45]
                if not status_message:
                    status_message = "Initializing build environment..."

                char = SPIN_CHARS[spin_index % len(SPIN_CHARS)]
                _print_spinner_update(char, status_message)

                spin_index += 1
                time.sleep(0.25)

            if reader is not None:
                reader.close()

            returncode = process.wait()

        if returncode != 0:
            if sys.stdout.isatty():
                sys.stdout.write(
                    f"\r[✖] Loading AI Assistant... failed.{' ':50}\n\n"
                )
                sys.stdout.flush()

            print(
                f"{ANSI_RED}--- Last lines of build log ---{ANSI_RESET}",
                file=sys.stderr,
            )
            for line in _tail_lines(log_path, 25):
                print(line, file=sys.stderr)
            print(
                f"{ANSI_RED}-----------------------------{ANSI_RESET}",
                file=sys.stderr,
            )
            return returncode

        # The fifty trailing spaces clear any remaining spinner text.
        if sys.stdout.isatty():
            sys.stdout.write(f"\r[✔] Loading AI Assistant... done.{' ':50}\n")
            sys.stdout.flush()
        return 0
    finally:
        try:
            log_path.unlink()
        except OSError:
            pass


def run_container(
    workspace_hash: str,
    session_id: str,
    container_name: str,
    docker_gid: Optional[int],
    agent_dir: Path,
    debug: bool,
    assistant_args: list[str],
) -> int:
    """Run the AI assistant Docker container.

    Arguments:
        workspace_hash: Docker label for the workspace.
        session_id: Docker label for the session.
        container_name: Name to assign to the Docker container.
        docker_gid: Host Docker group GID to add to the container, or None.
        agent_dir: Directory containing the AI assistant helper files.
        debug: Whether to print the underlying Docker command to stderr.
        assistant_args: Additional arguments passed to the AI assistant.

    Returns:
        The exit code of the docker run process.
    """
    uid = os.getuid()
    gid = os.getgid()
    home = str(Path.home())
    cwd = os.getcwd()
    pulse_user_dir = f"/run/user/{uid}/pulse/native"

    command = [
        "docker",
        "run",
        "-it",
        "--rm",
        "--name",
        container_name,
        "--label",
        f"aider.dir={workspace_hash}",
        "--label",
        f"aider.session={session_id}",
        "--label",
        f"aider.hostpid={os.getpid()}",
        "--user",
        f"{uid}:{gid}",
    ]

    if docker_gid is not None:
        command.extend(["--group-add", str(docker_gid)])
    else:
        print(
            "Warning: host 'docker' group not found; skipping --group-add. "
            "Docker commands inside the container may fail with permission "
            "errors.",
            file=sys.stderr,
        )

    if Path("/dev/snd").exists():
        command.extend([
            "--group-add",
            "audio",
            "--device",
            "/dev/snd",
        ])

    # Docker-outside-of-Docker prerequisite: mounting a nonexistent socket
    # path makes the daemon create an empty directory in its place, which
    # silently breaks engine access inside the container.
    if not Path("/var/run/docker.sock").exists():
        print(
            "Warning: /var/run/docker.sock does not exist on the host; "
            "Docker commands inside the container will fail (e.g. when the "
            "host reaches its daemon through DOCKER_HOST).",
            file=sys.stderr,
        )

    command.extend([
        "-e",
        "HOME=/home",
        "-e",
        "PYTHONUNBUFFERED=1",
        # Docker-outside-of-Docker: the CLI and compose plugin inside the
        # container drive the host daemon through this socket, so compose
        # stacks started for debugging are siblings, not nested containers.
        "-v",
        "/var/run/docker.sock:/var/run/docker.sock",
        # Same-path bind mount is load-bearing: it gives aider access to the
        # application source code AND makes host paths in compose files and
        # aider config arguments resolve identically inside the container.
        "-v",
        f"{cwd}:{cwd}",
        "-w",
        cwd,
        # Lets the assistant reach ports published on the host (e.g. by
        # sibling compose stacks) via http://host.docker.internal:<port>.
        "--add-host",
        "host.docker.internal:host-gateway",
    ])

    bashrc = Path(home) / ".bashrc"
    gitconfig = Path(home) / ".gitconfig"
    docker_config = Path(home) / ".docker"
    cache_dir = Path(home) / ".cache" / "aider"
    cache_dir.mkdir(parents=True, exist_ok=True)

    if bashrc.exists():
        command.extend(["-v", f"{bashrc}:/home/.bashrc:ro"])

    if gitconfig.exists():
        command.extend(["-v", f"{gitconfig}:/home/.gitconfig:ro"])

    # Mounted read-only so `docker compose` inside the container can use the
    # host's registry credentials when pulling or building images.
    if docker_config.exists():
        command.extend(["-v", f"{docker_config}:/home/.docker:ro"])

    command.extend(["-v", f"{cache_dir}:/home/.cache"])

    if Path(pulse_user_dir).exists():
        command.extend([
            "-v",
            f"{pulse_user_dir}:{pulse_user_dir}",
            "-e",
            f"PULSE_SERVER=unix:{pulse_user_dir}",
        ])

    command.extend(["-v", "/dev/shm:/dev/shm"])

    tags_cache_dir = agent_dir / ".aider.tags.cache.v4"
    tags_cache_dir.mkdir(parents=True, exist_ok=True)
    command.extend([
        "-v",
        f"{tags_cache_dir}:{cwd}/.aider.tags.cache.v4",
    ])

    project_root = Path(cwd)
    env_file = project_root / ".env"
    agent_env_file = agent_dir / ".env"

    if env_file.exists():
        command.extend(["--env-file", str(env_file)])
    elif agent_env_file.exists():
        command.extend(["--env-file", str(agent_env_file)])

    command.append(AIDER_IMAGE)
    command.extend(["--chat-mode", "ask"])
    command.extend(_aider_config_args(agent_dir))

    # Keep aider metadata inside .agent rather than the project root. These
    # paths resolve inside the container because agent_dir sits under the
    # bind-mounted project root (enforced by _warn_agent_dir_location).
    command.extend([
        "--chat-history-file",
        str(agent_dir / ".aider.chat.history.md"),
        "--input-history-file",
        str(agent_dir / ".aider.input.history"),
    ])

    command.extend(assistant_args)

    _trace_command(command, debug)

    watchdog_pid = _start_container_watchdog(container_name, debug)
    try:
        try:
            return subprocess.run(command).returncode
        except FileNotFoundError:
            print(
                "Error: Docker CLI not found while starting assistant.",
                file=sys.stderr,
            )
            return 127
        except KeyboardInterrupt:
            _remove_container(container_name, debug)
            return 130
    finally:
        _stop_watchdog(watchdog_pid)


def main() -> int:
    """Orchestrate the AI assistant launch."""
    assistant_args = sys.argv[1:]
    debug = False

    while assistant_args and assistant_args[0] in ("-x", "--debug"):
        debug = True
        assistant_args.pop(0)

    if os.name != "posix":
        print("This assistant currently supports Linux only.", file=sys.stderr)
        return 1

    if not _docker_available(debug=debug):
        print(
            "Docker CLI is not available. Please install Docker and ensure it is accessible from PATH.",
            file=sys.stderr,
        )
        return 1

    project_root = Path.cwd()
    dir_name = project_root.name
    workspace_hash = hashlib.md5((str(project_root) + "\n").encode()).hexdigest()
    session_id = _resolve_session_id()
    container_name = (
        f"{TOOL_NAME}-{dir_name}-{workspace_hash[:8]}-{session_id}-{os.getpid()}"
    )
    docker_gid = _get_docker_gid()
    dockerfile_path = AGENT_DIR / "Dockerfile.aider"

    if not dockerfile_path.exists():
        print(
            f"Dockerfile.aider not found at {dockerfile_path}. Exiting.",
            file=sys.stderr,
        )
        return 1

    _warn_agent_dir_location(project_root)

    if _running_in_container():
        print(
            "Warning: the launcher appears to be running inside a container; "
            "skipping stale-container cleanup. The launcher must run on the "
            "host, where container aliveness can be checked reliably.",
            file=sys.stderr,
        )
    else:
        cleanup_containers(workspace_hash, debug=debug)

    # The Dockerfile performs no COPY, so the build context only needs the
    # Dockerfile itself. Using .agent (with its generated .dockerignore)
    # avoids shipping the whole repository to the daemon on every launch.
    _ensure_build_dockerignore(AGENT_DIR)

    cache_tag = _image_cache_tag(dockerfile_path, debug=debug)
    if debug:
        print(f"Image cache tag: {cache_tag}", file=sys.stderr)

    cache_hit = _image_exists(cache_tag, debug=debug)
    if cache_hit:
        command = ["docker", "tag", cache_tag, AIDER_IMAGE]
        _trace_command(command, debug)
        tag_result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        cache_hit = tag_result.returncode == 0

    if cache_hit:
        print(
            f"{ANSI_GREEN}[✔] Image up to date — skipping build ({cache_tag}).{ANSI_RESET}"
        )
        build_code = 0
    else:
        build_code = build_image(dockerfile_path, AGENT_DIR, debug=debug)
        if build_code == 0:
            command = ["docker", "tag", AIDER_IMAGE, cache_tag]
            _trace_command(command, debug)
            subprocess.run(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            # Once the base image is local its repo digests are known;
            # re-hash so the next run gets a stable, digest-aware tag.
            refreshed_tag = _image_cache_tag(dockerfile_path, debug=debug)
            if refreshed_tag != cache_tag:
                command = ["docker", "tag", AIDER_IMAGE, refreshed_tag]
                _trace_command(command, debug)
                subprocess.run(
                    command,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )

    if build_code != 0:
        return build_code

    aider_cache_dir = Path.home() / ".cache" / "aider"
    aider_cache_dir.mkdir(parents=True, exist_ok=True)

    result = run_container(
        workspace_hash,
        session_id,
        container_name,
        docker_gid,
        AGENT_DIR,
        debug,
        assistant_args,
    )

    tag_cache_mount_point = project_root / ".aider.tags.cache.v4"
    _remove_if_empty(tag_cache_mount_point)

    return result


if __name__ == "__main__":
    sys.exit(main())
