#!/usr/bin/env python3
"""Launch an AI assistant in a Docker container.

This module provides a command-line interface equivalent to the previous
ai-assistant.sh script. It handles optional Docker image builds, container
cleanup, and running the assistant in a Docker container with workspace
isolation, audio support, and Docker-outside-of-Docker capabilities.

When installed as part of the `.agent` directory, this script keeps all
helper files, the Docker build context, and all caches inside `.agent`,
while the project root is bind-mounted into the container at the identical
path and used as the container working directory. Two invariants follow
from this design:

1. Aider can read and edit application source code anywhere under the
   project root, because the root is mounted at the same path it has on
   the host.
2. `docker` / `docker compose` commands run from inside the container
   operate on the host daemon via the mounted docker.sock, and any
   bind-mount paths in compose files resolve correctly because the project
   root path is identical inside and outside the container.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
import tempfile
import time
from collections import deque
from pathlib import Path
from typing import Optional

TOOL_NAME = "ai-assistant"
AIDER_IMAGE = "aider-agent:latest"
BASE_IMAGE_FALLBACK = "paulgauthier/aider-full:latest"

ANSI_RED = "\033[31m"
ANSI_GREEN = "\033[32m"
ANSI_RESET = "\033[0m"
SPIN_CHARS = ["-", "\\", "|", "/", "."]

LOG_RE = re.compile(
    r"(?:RUN|COPY|FROM|Installing|Extracting|Downloading|Unpacking|"
    r"Setting up|Get:|added|CACHED|ERROR|error).*"
)

AGENT_DIR = Path(__file__).resolve().parent

DOCKERIGNORE_CONTENT = """\
# Auto-generated by ai_assistant.py.
# The Dockerfile performs no COPY instructions, so the build context is kept
# minimal (just the Dockerfile) to make builds fast on large projects.
# If you add COPY instructions, whitelist the required files below.
*
!Dockerfile.aider
"""


def _remove_if_empty(path: Path) -> None:
    """Remove a directory if it exists and is empty."""
    try:
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    except OSError:
        pass


def _docker_available() -> bool:
    """Return True when the docker CLI can be executed."""
    try:
        result = subprocess.run(
            ["docker", "version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _trace_command(command: list[str]) -> None:
    """Print a command to stderr when debug output is enabled."""
    print("+", " ".join(command), file=sys.stderr)


def _tail_lines(path: Path, count: int) -> list[str]:
    """Return up to the last count lines from a text file."""
    try:
        lines = path.read_text(errors="replace").splitlines()
    except FileNotFoundError:
        return []
    return lines[-count:] if count > 0 else lines


def _print_spinner_update(char: str, message: str) -> None:
    """Print a single-line spinner status update when stdout is a TTY."""
    if not sys.stdout.isatty():
        return
    sys.stdout.write(f"\r[{char}] Loading AI Assistant... {message:<50}")
    sys.stdout.flush()


def _get_docker_gid() -> Optional[int]:
    """Return the Docker group GID, or None when the group is unavailable."""
    try:
        import grp
        return grp.getgrnam("docker").gr_gid
    except (KeyError, ImportError):
        return None


def _aider_config_args(agent_dir: Path) -> list[str]:
    """Return Aider CLI flags for config files stored in agent_dir."""
    args: list[str] = []

    config_file = agent_dir / ".aider.conf.yml"
    if config_file.exists():
        args.extend(["--config", str(config_file)])

    model_settings_file = agent_dir / ".aider.model.settings.yml"
    if model_settings_file.exists():
        args.extend(["--model-settings-file", str(model_settings_file)])

    return args


def _base_repo_digests(image: str) -> str:
    """Return local repo digests for an image, or "" when unknown."""
    try:
        result = subprocess.run(
            [
                "docker",
                "image",
                "inspect",
                "--format",
                "{{range .RepoDigests}}{{.}} {{end}}",
                image,
            ],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return ""
    if result.returncode != 0:
        return ""
    return (result.stdout or "").strip()


def _base_image(dockerfile_path: Path) -> str:
    """Extract the FROM image reference from a Dockerfile."""
    try:
        for line in dockerfile_path.read_text(errors="replace").splitlines():
            stripped = line.strip()
            if stripped.upper().startswith("FROM"):
                for token in stripped.split()[1:]:
                    if not token.startswith("--"):
                        return token
    except OSError:
        pass
    return BASE_IMAGE_FALLBACK


def _image_cache_tag(dockerfile_path: Path) -> str:
    """Return a content-hash tag for the built image.

    Combines the Dockerfile bytes with the base image's repo digests, so the
    cache tag changes (triggering a rebuild) whenever either the Dockerfile
    or the upstream base image changes. Before the first local pull the base
    contributes "" to the hash; after a successful build the tag is
    recomputed and refreshed (see main()).
    """
    hasher = hashlib.sha256()
    try:
        hasher.update(dockerfile_path.read_bytes())
    except OSError:
        pass
    hasher.update(_base_repo_digests(_base_image(dockerfile_path)).encode())
    return f"aider-agent:c-{hasher.hexdigest()[:16]}"


def _image_exists(tag: str) -> bool:
    """Return True when a local Docker image exists for the given tag."""
    try:
        result = subprocess.run(
            ["docker", "image", "inspect", tag],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _ensure_build_dockerignore(agent_dir: Path) -> None:
    """Create a minimal .dockerignore in agent_dir when one is missing."""
    target = agent_dir / ".dockerignore"
    if target.exists():
        return
    try:
        target.write_text(DOCKERIGNORE_CONTENT)
    except OSError:
        pass


def _warn_agent_dir_location(project_root: Path) -> None:
    """Warn when .agent is not inside the project root.

    The container bind-mounts the project root at the same path. Aider config
    and history paths (which live in .agent) only resolve inside the container
    when .agent is a subdirectory of the project root.
    """
    try:
        AGENT_DIR.relative_to(project_root)
    except ValueError:
        print(
            "Warning: the .agent directory is outside the project root; "
            "aider config and history files may not be visible inside the "
            "container.",
            file=sys.stderr,
        )


def cleanup_containers(workspace_hash: str) -> None:
    """Remove all containers associated with the current workspace.

    Arguments:
        workspace_hash: Aider directory hash used as a Docker label.

    Returns:
        None
    """
    try:
        result = subprocess.run(
            [
                "docker",
                "ps",
                "-a",
                "--filter",
                f"label=aider.dir={workspace_hash}",
                "--format",
                "{{.ID}}",
            ],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        print("Warning: unable to locate the Docker CLI.", file=sys.stderr)
        return

    if result.returncode != 0:
        warning = (result.stderr or "").strip()
        if warning:
            print(f"Warning: unable to list Docker containers: {warning}", file=sys.stderr)
        else:
            print(
                f"Warning: docker ps exited with status {result.returncode}.",
                file=sys.stderr,
            )
        return

    container_ids = [
        line for line in (result.stdout or "").splitlines() if line.strip()
    ]
    for container_id in container_ids:
        subprocess.run(
            ["docker", "rm", "-f", container_id],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )


def build_image(
    dockerfile_path: Path,
    context_dir: Path,
    debug: bool = False,
) -> int:
    """Build the Docker image with a progressive status indicator.

    Arguments:
        dockerfile_path: Path to the project Dockerfile.
        context_dir: Docker build context directory. The Dockerfile contains
            no COPY instructions, so a minimal context (the .agent directory)
            keeps builds fast even for very large projects.
        debug: Whether to print the underlying Docker command to stderr.

    Returns:
        0 on success, otherwise the Docker build exit code.
    """
    log_handle = tempfile.NamedTemporaryFile(
        mode="w",
        prefix="ai-assistant-build-",
        suffix=".log",
        delete=False,
    )
    log_path = Path(log_handle.name)
    log_handle.close()

    try:
        command = [
            "docker",
            "build",
            "--progress=plain",
            "-t",
            AIDER_IMAGE,
            "-f",
            str(dockerfile_path),
            str(context_dir),
        ]
        if debug:
            _trace_command(command)

        env = os.environ.copy()
        env["DOCKER_BUILDKIT"] = "1"

        with log_path.open("w") as log_file:
            try:
                process = subprocess.Popen(
                    command,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                    env=env,
                )
            except FileNotFoundError:
                print(
                    f"{ANSI_RED}Docker CLI not found while building image.{ANSI_RESET}",
                    file=sys.stderr,
                )
                return 127

            # Incremental log tail: read only newly appended bytes each tick
            # instead of re-reading and re-scanning the whole log file.
            spin_index = 0
            tail: deque[str] = deque(maxlen=40)
            reader = None
            try:
                reader = log_path.open("rb")
            except OSError:
                reader = None

            while process.poll() is None:
                if reader is not None:
                    chunk = reader.read()
                    if chunk:
                        tail.extend(
                            chunk.decode("utf-8", errors="replace").splitlines()
                        )

                status_message = ""
                if tail:
                    status_message = next(
                        (line for line in reversed(tail) if LOG_RE.search(line)),
                        "",
                    )[:45]
                if not status_message:
                    status_message = "Initializing build environment..."

                char = SPIN_CHARS[spin_index % len(SPIN_CHARS)]
                _print_spinner_update(char, status_message)

                spin_index += 1
                time.sleep(0.25)

            if reader is not None:
                reader.close()

            returncode = process.wait()

        if returncode != 0:
            if sys.stdout.isatty():
                sys.stdout.write(
                    f"\r[✖] Loading AI Assistant... failed.{' ':50}\n\n"
                )
                sys.stdout.flush()

            print(
                f"{ANSI_RED}--- Last lines of build log ---{ANSI_RESET}",
                file=sys.stderr,
            )
            for line in _tail_lines(log_path, 25):
                print(line, file=sys.stderr)
            print(
                f"{ANSI_RED}-----------------------------{ANSI_RESET}",
                file=sys.stderr,
            )
            return returncode

        # The fifty trailing spaces clear any remaining spinner text.
        if sys.stdout.isatty():
            sys.stdout.write(f"\r[✔] Loading AI Assistant... done.{' ':50}\n")
            sys.stdout.flush()
        return 0
    finally:
        try:
            log_path.unlink()
        except OSError:
            pass


def run_container(
    workspace_hash: str,
    session_id: str,
    container_name: str,
    docker_gid: Optional[int],
    agent_dir: Path,
    debug: bool,
    assistant_args: list[str],
) -> int:
    """Run the AI assistant Docker container.

    Arguments:
        workspace_hash: Docker label for the workspace.
        session_id: Docker label for the session.
        container_name: Name to assign to the Docker container.
        docker_gid: Host Docker group GID to add to the container, or None.
        agent_dir: Directory containing the AI assistant helper files.
        debug: Whether to print the underlying Docker command to stderr.
        assistant_args: Additional arguments passed to the AI assistant.

    Returns:
        The exit code of the docker run process.
    """
    uid = os.getuid()
    gid = os.getgid()
    home = str(Path.home())
    cwd = os.getcwd()
    pulse_user_dir = f"/run/user/{uid}/pulse/native"

    command = [
        "docker",
        "run",
        "-it",
        "--rm",
        "--name",
        container_name,
        "--label",
        f"aider.dir={workspace_hash}",
        "--label",
        f"aider.session={session_id}",
        "--user",
        f"{uid}:{gid}",
    ]

    if docker_gid is not None:
        command.extend(["--group-add", str(docker_gid)])

    if Path("/dev/snd").exists():
        command.extend([
            "--group-add",
            "audio",
            "--device",
            "/dev/snd",
        ])

    command.extend([
        "-e",
        "HOME=/home",
        "-e",
        "PYTHONUNBUFFERED=1",
        # Docker-outside-of-Docker: the CLI and compose plugin inside the
        # container drive the host daemon through this socket, so compose
        # stacks started for debugging are siblings, not nested containers.
        "-v",
        "/var/run/docker.sock:/var/run/docker.sock",
        # Same-path bind mount is load-bearing: it gives aider access to the
        # application source code AND makes host paths in compose files and
        # aider config arguments resolve identically inside the container.
        "-v",
        f"{cwd}:{cwd}",
        "-w",
        cwd,
        # Lets the assistant reach ports published on the host (e.g. by
        # sibling compose stacks) via http://host.docker.internal:<port>.
        "--add-host",
        "host.docker.internal:host-gateway",
    ])

    bashrc = Path(home) / ".bashrc"
    gitconfig = Path(home) / ".gitconfig"
    docker_config = Path(home) / ".docker"
    cache_dir = Path(home) / ".cache" / "aider"
    cache_dir.mkdir(parents=True, exist_ok=True)

    if bashrc.exists():
        command.extend(["-v", f"{bashrc}:/home/.bashrc:ro"])

    if gitconfig.exists():
        command.extend(["-v", f"{gitconfig}:/home/.gitconfig:ro"])

    # Mounted read-only so `docker compose` inside the container can use the
    # host's registry credentials when pulling or building images.
    if docker_config.exists():
        command.extend(["-v", f"{docker_config}:/home/.docker:ro"])

    command.extend(["-v", f"{cache_dir}:/home/.cache"])

    if Path(pulse_user_dir).exists():
        command.extend([
            "-v",
            f"{pulse_user_dir}:{pulse_user_dir}",
            "-e",
            f"PULSE_SERVER=unix:{pulse_user_dir}",
        ])

    command.extend(["-v", "/dev/shm:/dev/shm"])

    tags_cache_dir = agent_dir / ".aider.tags.cache.v4"
    tags_cache_dir.mkdir(parents=True, exist_ok=True)
    command.extend([
        "-v",
        f"{tags_cache_dir}:{cwd}/.aider.tags.cache.v4",
    ])

    project_root = Path(cwd)
    env_file = project_root / ".env"
    agent_env_file = agent_dir / ".env"

    if env_file.exists():
        command.extend(["--env-file", str(env_file)])
    elif agent_env_file.exists():
        command.extend(["--env-file", str(agent_env_file)])

    command.append(AIDER_IMAGE)
    command.extend(["--chat-mode", "ask"])
    command.extend(_aider_config_args(agent_dir))

    # Keep aider metadata inside .agent rather than the project root. These
    # paths resolve inside the container because agent_dir sits under the
    # bind-mounted project root (enforced by _warn_agent_dir_location).
    command.extend([
        "--chat-history-file",
        str(agent_dir / ".aider.chat.history.md"),
        "--input-history-file",
        str(agent_dir / ".aider.input.history"),
        "--aiderignore",
        str(agent_dir / ".aiderignore"),
        "--model-metadata-file",
        str(agent_dir / ".aider.model.metadata.json"),
    ])

    command.extend(assistant_args)

    if debug:
        _trace_command(command)

    try:
        return subprocess.run(command).returncode
    except FileNotFoundError:
        print(
            "Error: Docker CLI not found while starting assistant.",
            file=sys.stderr,
        )
        return 127


def main() -> int:
    """Orchestrate the AI assistant launch."""
    assistant_args = sys.argv[1:]
    debug = False

    while assistant_args and assistant_args[0] in ("-x", "--debug"):
        debug = True
        assistant_args.pop(0)

    if os.name != "posix":
        print("This assistant currently supports Linux only.", file=sys.stderr)
        return 1

    if not _docker_available():
        print(
            "Docker CLI is not available. Please install Docker and ensure it is accessible from PATH.",
            file=sys.stderr,
        )
        return 1

    project_root = Path.cwd()
    dir_name = project_root.name
    workspace_hash = hashlib.md5((str(project_root) + "\n").encode()).hexdigest()
    session_id = os.environ.get("VSCODE_PID", "0")
    container_name = (
        f"{TOOL_NAME}-{dir_name}-{workspace_hash[:8]}-{session_id}-{os.getpid()}"
    )
    docker_gid = _get_docker_gid()
    dockerfile_path = AGENT_DIR / "Dockerfile.aider"

    if not dockerfile_path.exists():
        print(
            f"Dockerfile.aider not found at {dockerfile_path}. Exiting.",
            file=sys.stderr,
        )
        return 1

    _warn_agent_dir_location(project_root)

    cleanup_containers(workspace_hash)

    # The Dockerfile performs no COPY, so the build context only needs the
    # Dockerfile itself. Using .agent (with its generated .dockerignore)
    # avoids shipping the whole repository to the daemon on every launch.
    _ensure_build_dockerignore(AGENT_DIR)

    cache_tag = _image_cache_tag(dockerfile_path)
    if debug:
        print(f"Image cache tag: {cache_tag}", file=sys.stderr)

    cache_hit = _image_exists(cache_tag)
    if cache_hit:
        tag_result = subprocess.run(
            ["docker", "tag", cache_tag, AIDER_IMAGE],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        cache_hit = tag_result.returncode == 0

    if cache_hit:
        print(
            f"{ANSI_GREEN}[✔] Image up to date — skipping build ({cache_tag}).{ANSI_RESET}"
        )
        build_code = 0
    else:
        build_code = build_image(dockerfile_path, AGENT_DIR, debug=debug)
        if build_code == 0:
            subprocess.run(
                ["docker", "tag", AIDER_IMAGE, cache_tag],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            # Once the base image is local its repo digests are known;
            # re-hash so the next run gets a stable, digest-aware tag.
            refreshed_tag = _image_cache_tag(dockerfile_path)
            if refreshed_tag != cache_tag:
                subprocess.run(
                    ["docker", "tag", AIDER_IMAGE, refreshed_tag],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )

    if build_code != 0:
        return build_code

    aider_cache_dir = Path.home() / ".cache" / "aider"
    aider_cache_dir.mkdir(parents=True, exist_ok=True)

    result = run_container(
        workspace_hash,
        session_id,
        container_name,
        docker_gid,
        AGENT_DIR,
        debug,
        assistant_args,
    )

    tag_cache_mount_point = project_root / ".aider.tags.cache.v4"
    _remove_if_empty(tag_cache_mount_point)

    return result


if __name__ == "__main__":
    sys.exit(main())