#!/usr/bin/env python3
"""Launch an AI assistant in a Docker container.

This module provides a command-line interface equivalent to the previous
ai-assistant.sh script. It handles optional Docker image builds, container
cleanup, and running the assistant in a Docker container with workspace
isolation, audio support, and Docker-outside-of-Docker capabilities.

When installed as part of the `.agent` directory, this script keeps all
helper files, the Docker build context, and all caches inside `.agent`,
while the project root is bind-mounted into the container at the identical
path and used as the container working directory. Two invariants follow
from this design:

1. Aider can read and edit application source code anywhere under the
   project root, because the root is mounted at the same path it has on
   the host.
2. `docker` / `docker compose` commands run from inside the container
   operate on the host daemon via the mounted docker.sock, and any
   bind-mount paths in compose files resolve correctly because the project
   root path is identical inside and outside the container.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import signal
import subprocess
import sys
import tempfile
import threading
import time
from collections import deque
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

TOOL_NAME = "ai-assistant"
AIDER_IMAGE = "aider-agent:latest"
BASE_IMAGE_FALLBACK = "paulgauthier/aider-full:latest"
SESSION_ID_ENV_VAR = "AI_ASSISTANT_SESSION_ID"

# Per-session engine-command log. Configured once in main() from the
# workspace hash + session ID; every traced command is appended so runs
# stay auditable regardless of debug mode. None until configured.
COMMAND_LOG_PATH: Optional[Path] = None

# How many recent command-log lines to surface at failure checkpoints.
COMMAND_LOG_TAIL_LINES = 10

# Well-known provider credential variables forwarded from the host
# environment into the container by name only (docker run -e VAR). Docker
# fills the value from the launcher process's own environment, so secrets
# never appear in commands or their debug traces (see run_container).
CREDENTIAL_ENV_VARS = (
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "OPENROUTER_API_KEY",
    "AZURE_API_KEY",
    "DEEPSEEK_API_KEY",
    "GROQ_API_KEY",
    "MISTRAL_API_KEY",
    "COHERE_API_KEY",
    "TOGETHER_API_KEY",
    "HF_TOKEN",
)

# GitHub's published SSH host keys and their officially published SHA256
# fingerprints. The rsa key is not pinned (too long to embed safely);
# modern clients negotiate GitHub's ed25519 host key first. A key is
# appended to the host known_hosts only when its computed fingerprint
# matches the published one, so a tampered source can never inject a
# host key (see _ensure_github_known_hosts).
GITHUB_ED25519_KEY = (
    "AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabg"
    "H5C9okWi0dh2l9GKJl"
)
GITHUB_ECDSA_KEY = (
    "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAA"
    "BBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRg"
    "g6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
)
GITHUB_ED25519_FINGERPRINT = (
    "SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU"
)
GITHUB_ECDSA_FINGERPRINT = (
    "SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM"
)

ANSI_RED = "\033[31m"
ANSI_GREEN = "\033[32m"
ANSI_RESET = "\033[0m"
SPIN_CHARS = ["-", "\\", "|", "/", "."]

LOG_RE = re.compile(
    r"(?:RUN|COPY|FROM|Installing|Extracting|Downloading|Unpacking|"
    r"Setting up|Get:|added|CACHED|ERROR|error).*"
)

AGENT_DIR = Path(__file__).resolve().parent

DOCKERIGNORE_CONTENT = """\
# Auto-generated by ai_assistant.py.
# The Dockerfile performs no COPY instructions, so the build context is kept
# minimal (just the Dockerfile) to make builds fast on large projects.
# If you add COPY instructions, whitelist the required files below.
*
!Dockerfile.aider
"""


def _remove_if_empty(path: Path) -> None:
    """Remove a file or directory if it exists and is empty."""
    try:
        if path.is_dir():
            if not any(path.iterdir()):
                path.rmdir()
        elif path.is_file() and path.stat().st_size == 0:
            path.unlink()
    except OSError:
        pass


def _cleanup_empty_artifacts(project_root: Path, agent_dir: Path) -> None:
    """Remove known launcher artifacts that are empty after a session.

    Conservative by design: only the launcher's own artifact paths are
    checked, never a repository-wide scan. Artifacts left by an abnormally
    killed launcher are re-checked and removed at the next session's exit.
    Anything that contains content is left untouched (see _remove_if_empty).
    """
    _remove_if_empty(project_root / ".aider.tags.cache.v4")
    _remove_if_empty(agent_dir / ".aider.tags.cache.v4")
    _remove_if_empty(agent_dir / ".aider.chat.history.md")
    _remove_if_empty(agent_dir / ".aider.input.history")


def _docker_available(debug: bool = False) -> bool:
    """Return True when the docker CLI can be executed."""
    command = ["docker", "version"]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _trace_command(command: list[str], debug: bool) -> None:
    """Append a command to the session log; print it when debug is enabled.

    Engine commands reference credential variables by name only (Docker
    fills the values from this process's environment; see run_container),
    so the log never contains secret values.
    """
    line = "+ " + " ".join(command)
    if COMMAND_LOG_PATH is not None:
        try:
            COMMAND_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
            # 0600 on creation and afterwards: the log lives in a shared
            # temp directory and must stay private to the launching user
            # (chmod also tightens files created by older versions).
            fd = os.open(
                COMMAND_LOG_PATH,
                os.O_WRONLY | os.O_CREAT | os.O_APPEND,
                0o600,
            )
            os.chmod(COMMAND_LOG_PATH, 0o600)
            with os.fdopen(fd, "a", encoding="utf-8") as log_file:
                log_file.write(line + "\n")
        except OSError:
            pass
    if debug:
        print(line, file=sys.stderr)


def _configure_command_log(workspace_hash: str, session_id: str) -> Path:
    """Point the command log at a predictable per-session file.

    The file name is derived from the workspace hash and session ID, so the
    location is stable for a given session. The file is created on first
    write and appended to afterwards, never truncated.
    """
    global COMMAND_LOG_PATH
    COMMAND_LOG_PATH = (
        Path(tempfile.gettempdir())
        / f"ai-assistant-{workspace_hash[:8]}-{session_id}.log"
    )
    return COMMAND_LOG_PATH


def _dump_recent_log_lines(debug: bool) -> None:
    """Surface the most recent command-log entries when debug is enabled."""
    if not debug or COMMAND_LOG_PATH is None:
        return
    recent = _tail_lines(COMMAND_LOG_PATH, COMMAND_LOG_TAIL_LINES)
    if not recent:
        return
    print("--- Recent command log entries ---", file=sys.stderr)
    for line in recent:
        print(line, file=sys.stderr)


def _tail_lines(path: Path, count: int) -> list[str]:
    """Return up to the last count lines from a text file."""
    try:
        lines = path.read_text(errors="replace").splitlines()
    except FileNotFoundError:
        return []
    return lines[-count:] if count > 0 else lines


def _print_spinner_update(char: str, message: str) -> None:
    """Print a single-line spinner status update when stdout is a TTY."""
    if not sys.stdout.isatty():
        return
    sys.stdout.write(f"\r[{char}] Loading AI Assistant... {message:<50}")
    sys.stdout.flush()


def _spin_worker(message: str, stop_event: threading.Event) -> None:
    """Animate the spinner until stop_event is set."""
    spin_index = 0
    while True:
        char = SPIN_CHARS[spin_index % len(SPIN_CHARS)]
        _print_spinner_update(char, message)
        spin_index += 1
        if stop_event.wait(0.25):
            break


@contextmanager
def _spinner(message: str, debug: bool = False) -> Iterator[None]:
    """Show a single-line spinner while the wrapped operation runs.

    The spinner animates on a daemon thread and only when stdout is a
    TTY; it is skipped in debug mode so traced commands print cleanly.
    """
    active = not debug and sys.stdout.isatty()
    stop_event = threading.Event()
    thread = threading.Thread(
        target=_spin_worker,
        args=(message, stop_event),
        daemon=True,
    )
    if active:
        thread.start()
    try:
        yield
    finally:
        stop_event.set()
        if thread.is_alive():
            thread.join()
        if active:
            # Overwrite the spinner line with spaces, then return the
            # cursor to the start of the line.
            sys.stdout.write("\r" + " " * 80 + "\r")
            sys.stdout.flush()


def _get_docker_gid() -> Optional[int]:
    """Return the Docker group GID, or None when the group is unavailable."""
    try:
        import grp
        return grp.getgrnam("docker").gr_gid
    except (KeyError, ImportError):
        return None


# Configuration files the launcher supports merging with project-root
# counterparts (see _root_config_counterparts and _aider_config_args).
MERGEABLE_CONFIG_FILES = (
    ".aider.conf.yml",
    ".aider.model.settings.yml",
    ".aiderignore",
    ".aider.model.metadata.json",
)


def _root_config_counterparts(project_root: Path) -> dict[str, Path]:
    """Detect project-root counterparts of the mergeable config files.

    Checks the project root for same-named counterparts of each file in
    MERGEABLE_CONFIG_FILES. Detection is per file, so any mix of present
    and absent counterparts is handled correctly; only regular files count.

    Returns a mapping of file name to project-root path for every detected
    counterpart; empty when only the assistant-default copies exist.
    """
    return {
        name: project_root / name
        for name in MERGEABLE_CONFIG_FILES
        if (project_root / name).is_file()
    }


# Directory (under agent_dir) holding merged configuration intermediates.
# Intermediates are rewritten deterministically on each launch and removed
# when the session ends (see _remove_merged_intermediates).
MERGED_DIR_NAME = ".merged"

# CLI flag for each value-based mergeable config file. .aiderignore is
# handled separately: its patterns are union-merged (see _merge_aiderignore).
VALUE_CONFIG_FLAGS = {
    ".aider.conf.yml": "--config",
    ".aider.model.settings.yml": "--model-settings-file",
    ".aider.model.metadata.json": "--model-metadata-file",
}


def _deep_merge(base, override):
    """Combine nested structures level by level; override wins conflicts.

    dict+dict merges recursively; any other combination resolves to the
    override value. Inputs are never mutated; a new structure is returned.
    """
    if isinstance(base, dict) and isinstance(override, dict):
        merged = dict(base)
        for key, value in override.items():
            if key in merged:
                merged[key] = _deep_merge(merged[key], value)
            else:
                merged[key] = value
        return merged
    return override


def _merge_model_settings(base, override):
    """Merge model-settings documents keyed by entry name.

    Both documents are normally lists of model entries. Entries sharing a
    name are merged (project root wins conflicts); agent-only entries are
    retained in place; root-only entries are appended in their original
    order. Non-list documents fall back to _deep_merge.
    """
    if not isinstance(base, list) or not isinstance(override, list):
        return _deep_merge(base, override)
    merged = list(base)
    for entry in override:
        if isinstance(entry, dict) and "name" in entry:
            for index, existing in enumerate(merged):
                if isinstance(existing, dict) and existing.get("name") == entry["name"]:
                    merged[index] = _deep_merge(existing, entry)
                    break
            else:
                merged.append(entry)
        else:
            merged.append(entry)
    return merged


def _merge_value_documents(name: str, agent_doc, root_doc):
    """Dispatch the merge strategy for one value-based config file."""
    if name == ".aider.model.settings.yml":
        return _merge_model_settings(agent_doc, root_doc)
    return _deep_merge(agent_doc, root_doc)


def _merge_json_documents(agent_file: Path, root_file: Path):
    """Load and deep-merge two JSON documents; the root document wins."""
    with agent_file.open(encoding="utf-8") as handle:
        agent_doc = json.load(handle)
    with root_file.open(encoding="utf-8") as handle:
        root_doc = json.load(handle)
    return _deep_merge(agent_doc, root_doc)


def _yaml_entries(text: str) -> list[list]:
    """Return [indent, content] pairs for the meaningful lines of a document.

    Raises ValueError for syntax outside the supported subset (document
    markers, directives, tab indentation).
    """
    entries: list[list] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped in ("---", "...") or stripped.startswith("%"):
            raise ValueError("document markers are outside the supported subset")
        leading = raw[: len(raw) - len(raw.lstrip())]
        if "\t" in leading:
            raise ValueError("tab indentation is outside the supported subset")
        entries.append([len(leading), stripped])
    return entries


def _yaml_split_key(content: str) -> tuple[str, str]:
    """Split a 'key: value' line into (key, rest); rest may be empty."""
    if content[:1] in ('"', "'"):
        quote = content[0]
        end = content.find(quote, 1)
        if end == -1:
            raise ValueError("unterminated quoted key")
        rest = content[end + 1 :]
        if not rest.startswith(":"):
            raise ValueError("expected ':' after a quoted key")
        return content[1:end], rest[1:].strip()
    for index, char in enumerate(content):
        if char == ":" and (index + 1 == len(content) or content[index + 1] == " "):
            return content[:index].strip(), content[index + 1 :].strip()
    raise ValueError("line is not a mapping entry")


def _strip_inline_comment(text: str) -> str:
    """Drop an unquoted trailing '# ...' comment from a scalar."""
    if text[:1] in ('"', "'"):
        return text
    for index, char in enumerate(text):
        if char == "#" and (index == 0 or text[index - 1] == " "):
            return text[:index].rstrip()
    return text


def _yaml_scalar(text: str):
    """Convert a scalar token to a Python value.

    Raises ValueError for syntax outside the supported subset (flow style,
    anchors, aliases, tags, block scalars) so callers can fall back to
    single-file pass-through.
    """
    stripped = text.strip()
    if not stripped:
        return None
    if stripped[:1] in ("{", "[", "&", "*", "!", "|", ">"):
        raise ValueError("syntax outside the supported YAML subset")
    if stripped[:1] in ('"', "'"):
        quote = stripped[0]
        end = stripped.find(quote, 1)
        if end == -1:
            raise ValueError("unterminated quoted scalar")
        return stripped[1:end]
    lowered = stripped.lower()
    if lowered in ("null", "~"):
        return None
    if lowered in ("true", "yes", "on"):
        return True
    if lowered in ("false", "no", "off"):
        return False
    try:
        return int(stripped, 10)
    except ValueError:
        pass
    try:
        return float(stripped)
    except ValueError:
        pass
    return stripped


def _yaml_parse(entries: list[list], pos: int, indent: int):
    """Parse one block (mapping or sequence) at the given indent.

    Returns (value, next_pos). Raises ValueError on unexpected indentation
    or syntax outside the supported subset.
    """
    if pos >= len(entries) or entries[pos][0] != indent:
        raise ValueError("unexpected indentation")
    if entries[pos][1] == "-" or entries[pos][1].startswith("- "):
        items = []
        while (
            pos < len(entries)
            and entries[pos][0] == indent
            and (entries[pos][1] == "-" or entries[pos][1].startswith("- "))
        ):
            raw_payload = entries[pos][1][1:].lstrip()
            pos += 1
            if not raw_payload:
                if pos < len(entries) and entries[pos][0] > indent:
                    value, pos = _yaml_parse(entries, pos, entries[pos][0])
                    items.append(value)
                else:
                    items.append(None)
                continue
            payload = _strip_inline_comment(raw_payload)
            try:
                _yaml_split_key(payload)
            except ValueError:
                items.append(_yaml_scalar(payload))
                continue
            # Sequence of mappings: re-anchor the payload as the first line
            # of a mapping whose indent is the payload's own column.
            item_indent = indent + (len(entries[pos - 1][1]) - len(raw_payload))
            entries[pos - 1] = [item_indent, payload]
            value, pos = _yaml_parse(entries, pos - 1, item_indent)
            items.append(value)
        return items, pos

    mapping: dict = {}
    while pos < len(entries) and entries[pos][0] == indent:
        content = entries[pos][1]
        if content == "-" or content.startswith("- "):
            break
        key, rest = _yaml_split_key(content)
        pos += 1
        rest = _strip_inline_comment(rest)
        if rest:
            mapping[key] = _yaml_scalar(rest)
        elif pos < len(entries) and entries[pos][0] > indent:
            mapping[key], pos = _yaml_parse(entries, pos, entries[pos][0])
        else:
            mapping[key] = None
    return mapping, pos


def _yaml_load(text: str):
    """Parse a minimal YAML subset into Python structures.

    Supports block mappings, block sequences (including sequences of
    mappings), nested indentation, comments, and plain or quoted scalars.
    Raises ValueError for syntax outside the subset (flow style, anchors,
    aliases, tags, block scalars, document markers, tab indentation) so
    callers can fall back to single-file pass-through.
    """
    entries = _yaml_entries(text)
    if not entries:
        return {}
    value, pos = _yaml_parse(entries, 0, entries[0][0])
    if pos != len(entries):
        raise ValueError("trailing content outside the supported subset")
    return value


def _yaml_scalar_text(value) -> str:
    """Render a scalar deterministically, quoting whenever required."""
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    quoted = not text or text != text.strip()
    if not quoted:
        quoted = text.lower() in (
            "null",
            "~",
            "true",
            "false",
            "yes",
            "no",
            "on",
            "off",
        )
    if not quoted:
        try:
            int(text, 10)
            quoted = True
        except ValueError:
            pass
    if not quoted:
        try:
            float(text)
            quoted = True
        except ValueError:
            pass
    if not quoted:
        quoted = text.startswith(("- ", ": ", "? ")) or any(
            char in text for char in ":#{}[]&*!|>%@`\"',"
        )
    if quoted:
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


def _yaml_dump_lines(value, indent: int) -> list[str]:
    """Render a parsed document as deterministic YAML lines."""
    pad = " " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            key_text = _yaml_scalar_text(str(key))
            if isinstance(item, (dict, list)) and item:
                lines.append(f"{pad}{key_text}:")
                lines.extend(_yaml_dump_lines(item, indent + 2))
            elif isinstance(item, dict):
                lines.append(f"{pad}{key_text}: {{}}")
            elif isinstance(item, list):
                lines.append(f"{pad}{key_text}: []")
            else:
                lines.append(f"{pad}{key_text}: {_yaml_scalar_text(item)}")
        return lines
    if isinstance(value, list):
        for item in value:
            if isinstance(item, (dict, list)) and item:
                item_lines = _yaml_dump_lines(item, indent + 2)
                lines.append(f"{pad}- {item_lines[0].lstrip()}")
                lines.extend(item_lines[1:])
            elif isinstance(item, dict):
                lines.append(f"{pad}- {{}}")
            elif isinstance(item, list):
                lines.append(f"{pad}- []")
            else:
                lines.append(f"{pad}- {_yaml_scalar_text(item)}")
        return lines
    return [f"{pad}{_yaml_scalar_text(value)}"]


def _yaml_dump(value) -> str:
    """Serialize a parsed document deterministically across runs."""
    return "\n".join(_yaml_dump_lines(value, 0)) + "\n"


def _write_merged_value_file(
    agent_dir: Path,
    name: str,
    agent_file: Path,
    root_file: Path,
    debug: bool,
) -> Optional[Path]:
    """Combine an agent default with its project-root counterpart.

    Writes the combined document to a deterministic intermediate path under
    agent_dir/.merged and returns it. Returns None when either side cannot
    be parsed or the intermediate cannot be written; the caller then falls
    back to single-file pass-through so a launch is never broken.
    """
    try:
        if name == ".aider.model.metadata.json":
            merged_doc = _merge_json_documents(agent_file, root_file)
            serialized = json.dumps(merged_doc, indent=2) + "\n"
        else:
            agent_doc = _yaml_load(agent_file.read_text(encoding="utf-8"))
            root_doc = _yaml_load(root_file.read_text(encoding="utf-8"))
            merged_doc = _merge_value_documents(name, agent_doc, root_doc)
            serialized = _yaml_dump(merged_doc)
    except (OSError, ValueError, RecursionError):
        if debug:
            print(
                f"Warning: could not merge {name}; using the assistant default.",
                file=sys.stderr,
            )
        return None

    merged_path = agent_dir / MERGED_DIR_NAME / name
    try:
        merged_path.parent.mkdir(parents=True, exist_ok=True)
        existing = (
            merged_path.read_text(encoding="utf-8") if merged_path.exists() else None
        )
        if existing != serialized:
            merged_path.write_text(serialized, encoding="utf-8")
    except (OSError, ValueError):
        if debug:
            print(
                f"Warning: could not write the merged {name}; using the "
                "assistant default.",
                file=sys.stderr,
            )
        return None
    return merged_path


def _merge_aiderignore(agent_file: Path, root_file: Path) -> list[str]:
    """Return the union of ignore patterns from both files.

    Blank lines and comment lines are excluded. Agent patterns keep their
    original order first, then root-only patterns in their original order,
    so the result is deterministic for identical inputs; duplicates are
    counted once. Trailing whitespace is dropped (not significant in
    gitignore syntax); everything else is preserved as-is, including
    negation patterns.

    Raises OSError when either file cannot be read, so the caller can fall
    back to single-file pass-through instead of losing one side's patterns.
    """
    patterns: list[str] = []
    seen: set[str] = set()
    for file in (agent_file, root_file):
        for line in file.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            pattern = line.rstrip()
            if pattern not in seen:
                seen.add(pattern)
                patterns.append(pattern)
    return patterns


def _write_merged_ignore_file(
    agent_dir: Path,
    agent_file: Path,
    root_file: Path,
    debug: bool,
) -> Optional[Path]:
    """Combine both ignore files into one deterministic intermediate.

    Writes the union of patterns to agent_dir/.merged/.aiderignore and
    returns it. Returns None when either file cannot be read or the
    intermediate cannot be written; the caller then falls back to the
    agent copy so a launch is never broken.
    """
    try:
        patterns = _merge_aiderignore(agent_file, root_file)
        serialized = "\n".join(patterns) + "\n"
        merged_path = agent_dir / MERGED_DIR_NAME / ".aiderignore"
        merged_path.parent.mkdir(parents=True, exist_ok=True)
        existing = (
            merged_path.read_text(encoding="utf-8") if merged_path.exists() else None
        )
        if existing != serialized:
            merged_path.write_text(serialized, encoding="utf-8")
    except OSError:
        if debug:
            print(
                "Warning: could not merge .aiderignore; using the assistant "
                "default.",
                file=sys.stderr,
            )
        return None
    return merged_path


def _merged_config_args(
    agent_dir: Path,
    root_counterparts: dict[str, Path],
    debug: bool,
) -> list[str]:
    """Return Aider config flags with project-root merging applied.

    For each value-based config file:
    - both copies present -> the flag points at the merged intermediate
    - only the agent copy -> unchanged pass-through to the agent copy
    - only the root counterpart -> the flag points at the root file directly,
      which is already a complete, deliberately placed configuration
    - unmergeable pair -> fall back to the agent copy (reported in debug)

    .aiderignore follows the same rules with a union merge: both copies
    present -> the flag points at an intermediate holding the union of
    patterns from both files (see _merge_aiderignore).

    With no counterparts at all this is exactly _aider_config_args.
    """
    if not root_counterparts:
        return _aider_config_args(agent_dir)

    args: list[str] = []

    aiderignore_file = agent_dir / ".aiderignore"
    root_ignore_file = root_counterparts.get(".aiderignore")
    if aiderignore_file.exists() and root_ignore_file is not None:
        merged_ignore = _write_merged_ignore_file(
            agent_dir, aiderignore_file, root_ignore_file, debug
        )
        if merged_ignore is not None:
            args.extend(["--aiderignore", str(merged_ignore)])
        else:
            args.extend(["--aiderignore", str(aiderignore_file)])
    elif aiderignore_file.exists():
        args.extend(["--aiderignore", str(aiderignore_file)])
    elif root_ignore_file is not None:
        args.extend(["--aiderignore", str(root_ignore_file)])

    for name, flag in VALUE_CONFIG_FLAGS.items():
        agent_file = agent_dir / name
        root_file = root_counterparts.get(name)
        agent_exists = agent_file.exists()
        if agent_exists and root_file is not None:
            merged_path = _write_merged_value_file(
                agent_dir, name, agent_file, root_file, debug
            )
            if merged_path is not None:
                args.extend([flag, str(merged_path)])
            else:
                args.extend([flag, str(agent_file)])
        elif agent_exists:
            args.extend([flag, str(agent_file)])
        elif root_file is not None:
            args.extend([flag, str(root_file)])
    return args


def _remove_merged_intermediates(agent_dir: Path) -> None:
    """Remove the merged-config intermediate directory after a session.

    Intermediates are read by the assistant at startup only, so removing
    them at session end is safe; the next launch rewrites them
    deterministically from the same inputs.
    """
    merged_dir = agent_dir / MERGED_DIR_NAME
    try:
        if not merged_dir.is_dir():
            return
        for child in merged_dir.iterdir():
            try:
                if child.is_file():
                    child.unlink()
            except OSError:
                pass
        merged_dir.rmdir()
    except OSError:
        pass


def _aider_config_args(agent_dir: Path) -> list[str]:
    """Return Aider CLI flags for config files stored in agent_dir."""
    args: list[str] = []

    config_file = agent_dir / ".aider.conf.yml"
    if config_file.exists():
        args.extend(["--config", str(config_file)])

    model_settings_file = agent_dir / ".aider.model.settings.yml"
    if model_settings_file.exists():
        args.extend(["--model-settings-file", str(model_settings_file)])

    aiderignore_file = agent_dir / ".aiderignore"
    if aiderignore_file.exists():
        args.extend(["--aiderignore", str(aiderignore_file)])

    model_metadata_file = agent_dir / ".aider.model.metadata.json"
    if model_metadata_file.exists():
        args.extend(["--model-metadata-file", str(model_metadata_file)])

    return args


def _base_repo_digests(image: str, debug: bool = False) -> str:
    """Return local repo digests for an image, or "" when unknown."""
    command = [
        "docker",
        "image",
        "inspect",
        "--format",
        "{{range .RepoDigests}}{{.}} {{end}}",
        image,
    ]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return ""
    if result.returncode != 0:
        return ""
    return (result.stdout or "").strip()


def _base_image(dockerfile_path: Path) -> str:
    """Extract the FROM image reference from a Dockerfile."""
    try:
        for line in dockerfile_path.read_text(errors="replace").splitlines():
            stripped = line.strip()
            if stripped.upper().startswith("FROM"):
                for token in stripped.split()[1:]:
                    if not token.startswith("--"):
                        return token
    except OSError:
        pass
    return BASE_IMAGE_FALLBACK


def _image_cache_tag(dockerfile_path: Path, debug: bool = False) -> str:
    """Return a content-hash tag for the built image.

    Combines the Dockerfile bytes with the base image's repo digests, so the
    cache tag changes (triggering a rebuild) whenever either the Dockerfile
    or the upstream base image changes. Before the first local pull the base
    contributes "" to the hash; after a successful build the tag is
    recomputed and refreshed (see main()).
    """
    hasher = hashlib.sha256()
    try:
        hasher.update(dockerfile_path.read_bytes())
    except OSError:
        pass
    hasher.update(_base_repo_digests(_base_image(dockerfile_path), debug).encode())
    return f"aider-agent:c-{hasher.hexdigest()[:16]}"


def _image_exists(tag: str, debug: bool = False) -> bool:
    """Return True when a local Docker image exists for the given tag."""
    command = ["docker", "image", "inspect", tag]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def _ensure_build_dockerignore(agent_dir: Path) -> None:
    """Create a minimal .dockerignore in agent_dir when one is missing."""
    target = agent_dir / ".dockerignore"
    if target.exists():
        return
    try:
        target.write_text(DOCKERIGNORE_CONTENT)
    except OSError:
        pass


def _warn_agent_dir_location(project_root: Path) -> None:
    """Warn when .agent is not inside the project root.

    The container bind-mounts the project root at the same path. Aider config
    and history paths (which live in .agent) only resolve inside the container
    when .agent is a subdirectory of the project root.
    """
    try:
        AGENT_DIR.relative_to(project_root)
    except ValueError:
        print(
            "Warning: the .agent directory is outside the project root; "
            "aider config and history files may not be visible inside the "
            "container.",
            file=sys.stderr,
        )


def _ssh_fingerprint(key_blob: str) -> Optional[str]:
    """Return the OpenSSH SHA256 fingerprint of a base64 key blob.

    Mirrors `ssh-keygen -lf` output: "SHA256:" plus unpadded base64 of
    the SHA256 digest over the decoded wire-format key blob.
    """
    try:
        decoded = base64.b64decode(key_blob, validate=True)
    except ValueError:
        return None
    digest = hashlib.sha256(decoded).digest()
    return "SHA256:" + base64.b64encode(digest).decode("ascii").rstrip("=")


def _ensure_github_known_hosts(debug: bool) -> None:
    """Pin GitHub's published SSH host keys in the host known_hosts file.

    Appends a key only when its computed SHA256 fingerprint matches the
    published fingerprint and the blob is not already present, so the
    file is never rewritten and a tampered source cannot inject a host
    key. Best-effort and non-fatal: failure only means ssh may prompt on
    the next push.
    """
    candidates = [
        ("ssh-ed25519", GITHUB_ED25519_KEY, GITHUB_ED25519_FINGERPRINT),
        ("ecdsa-sha2-nistp256", GITHUB_ECDSA_KEY, GITHUB_ECDSA_FINGERPRINT),
    ]
    ssh_dir = Path.home() / ".ssh"
    known_hosts = ssh_dir / "known_hosts"
    try:
        ssh_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        existing = (
            known_hosts.read_text(encoding="utf-8", errors="replace")
            if known_hosts.exists()
            else ""
        )
    except OSError as exc:
        print(f"Warning: cannot update {known_hosts}: {exc}", file=sys.stderr)
        return
    additions = [
        f"github.com {key_type} {blob}\n"
        for key_type, blob, fingerprint in candidates
        if _ssh_fingerprint(blob) == fingerprint and blob not in existing
    ]
    if not additions:
        return
    try:
        with known_hosts.open("a", encoding="utf-8") as handle:
            handle.writelines(additions)
    except OSError as exc:
        print(f"Warning: cannot update {known_hosts}: {exc}", file=sys.stderr)
        return
    if debug:
        print(
            f"Pinned {len(additions)} GitHub host key(s) in {known_hosts}.",
            file=sys.stderr,
        )


def _container_passwd_home(cache_tag: str, debug: bool) -> Optional[str]:
    """Return the passwd home directory of the runtime uid in the image.

    OpenSSH resolves default identity and known_hosts paths from the
    passwd home (pw_dir), not from $HOME, so the host ~/.ssh mount must
    target pw_dir for key authentication to work without explicit -i
    flags. The value is discovered with a one-shot container and cached
    in the host aider cache keyed by the image cache tag. Returns None
    when the lookup fails; the caller then keeps the legacy /home mount
    only.
    """
    cache_path = Path.home() / ".cache" / "aider" / ".container-home"
    prefix = f"{cache_tag} "
    try:
        cached = cache_path.read_text(encoding="utf-8").splitlines()
        if cached and cached[0].startswith(prefix):
            home = cached[0][len(prefix):]
            if home.startswith("/") and home != "/":
                return home
    except OSError:
        pass
    uid = os.getuid()
    command = [
        "docker",
        "run",
        "--rm",
        "--entrypoint",
        "/bin/sh",
        AIDER_IMAGE,
        "-c",
        f"grep '^{uid}:' /etc/passwd | cut -d: -f6",
    ]
    _trace_command(command, debug)
    try:
        result = subprocess.run(
            command,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        if debug:
            print(
                f"Note: could not query the container home: {exc}",
                file=sys.stderr,
            )
        return None
    home = (result.stdout or "").strip()
    if result.returncode != 0 or not home.startswith("/") or home == "/":
        if debug:
            print(
                f"Note: no passwd home for uid {uid} in {AIDER_IMAGE}; "
                "SSH keys will be mounted at /home/.ssh only.",
                file=sys.stderr,
            )
        return None
    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(f"{cache_tag} {home}\n", encoding="utf-8")
    except OSError:
        pass
    return home


def _resolve_session_id() -> str:
    """Return the session identifier used for container naming and labels.

    Resolution order:
    1. The AI_ASSISTANT_SESSION_ID environment override, so any editor or
       shell can group multiple terminals into a single session.
    2. The tmux session identity (TMUX is shared by all panes of a session).
    3. The GNU screen session name (STY).
    4. The parent shell PID, giving each plain terminal its own session.

    Returns:
        A session identifier restricted to Docker's legal container-name
        characters, because the value is embedded in the container name.
    """
    override = os.environ.get(SESSION_ID_ENV_VAR)
    if override:
        raw = override
    elif os.environ.get("TMUX"):
        # TMUX holds "<socket>,<server-pid>,<session>,..." and is shared by
        # every pane attached to the same tmux session.
        raw = "tmux-" + os.environ["TMUX"]
    elif os.environ.get("STY"):
        raw = "screen-" + os.environ["STY"]
    else:
        raw = str(os.getppid())
    return re.sub(r"[^a-zA-Z0-9_.-]", "_", raw)


def _pid_alive(pid_text: str) -> bool:
    """Return True when the given host PID currently exists."""
    try:
        pid = int(pid_text)
    except (TypeError, ValueError):
        return False
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


def _remove_container(container_ref: str, debug: bool = False) -> None:
    """Force-remove a container by name or ID. Missing containers are ignored."""
    command = ["docker", "rm", "-f", container_ref]
    try:
        _trace_command(command, debug)
        subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        pass


def _set_parent_death_signal(sig: int) -> None:
    """Ask the kernel to signal this process when its parent dies."""
    try:
        import ctypes

        libc = ctypes.CDLL("libc.so.6", use_errno=True)
        pr_set_pdeathsig = 1
        libc.prctl.argtypes = [ctypes.c_int, ctypes.c_ulong]
        libc.prctl.restype = ctypes.c_int
        libc.prctl(pr_set_pdeathsig, sig)
    except (OSError, AttributeError):
        pass


def _start_container_watchdog(container_name: str, debug: bool = False) -> int:
    """Fork a child that removes the container if this process dies.

    Uses PR_SET_PDEATHSIG so SIGKILL of the launcher still stops the
    container, and polls getppid() as a fallback when prctl is unavailable.
    """
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        pid = os.fork()
    except OSError:
        return -1
    if pid > 0:
        return pid

    try:
        os.setsid()
    except OSError:
        try:
            os.setpgrp()
        except OSError:
            pass

    signal.signal(signal.SIGINT, signal.SIG_IGN)
    signal.signal(signal.SIGHUP, signal.SIG_IGN)
    parent = os.getppid()
    _set_parent_death_signal(signal.SIGTERM)

    def _cleanup(_signum=None, _frame=None):
        _remove_container(container_name, debug)
        os._exit(0)

    signal.signal(signal.SIGTERM, _cleanup)
    if os.getppid() != parent or os.getppid() == 1:
        _cleanup()
    while True:
        time.sleep(1)
        if os.getppid() != parent or os.getppid() == 1:
            _cleanup()


def _stop_watchdog(watchdog_pid: int) -> None:
    """Terminate a watchdog child started by _start_container_watchdog."""
    if watchdog_pid <= 0:
        return
    try:
        os.kill(watchdog_pid, signal.SIGKILL)
    except OSError:
        pass
    try:
        os.waitpid(watchdog_pid, 0)
    except OSError:
        pass


def _running_in_container() -> bool:
    """Return True when this launcher is itself running inside a container.

    Docker creates /.dockerenv in every container it starts, so the file's
    presence is a reliable marker for a nested launcher invocation. From
    inside a container the host PID space is invisible, so stale-container
    cleanup must not run (see cleanup_containers).
    """
    return Path("/.dockerenv").exists()


def cleanup_containers(
    workspace_hash: str,
    debug: bool = False,
) -> None:
    """Remove leftover containers whose host launcher process is not alive.

    Live launchers in the same workspace are left running so multiple
    terminals can coexist. Session identity is not used for cleanup.

    Arguments:
        workspace_hash: Aider directory hash used as a Docker label.
        debug: Whether to print the underlying Docker commands to stderr.

    Returns:
        None
    """
    command = [
        "docker",
        "ps",
        "-a",
        "--filter",
        f"label=aider.dir={workspace_hash}",
        "--format",
        '{{.ID}} {{.Label "aider.hostpid"}}',
    ]
    try:
        _trace_command(command, debug)
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        print("Warning: unable to locate the Docker CLI.", file=sys.stderr)
        return

    if result.returncode != 0:
        warning = (result.stderr or "").strip()
        if warning:
            print(f"Warning: unable to list Docker containers: {warning}", file=sys.stderr)
        else:
            print(
                f"Warning: docker ps exited with status {result.returncode}.",
                file=sys.stderr,
            )
        return

    stale_ids = []
    for line in (result.stdout or "").splitlines():
        fields = line.split()
        if not fields:
            continue
        # Unlabeled leftovers (no hostpid) are treated as orphaned.
        host_pid = fields[1] if len(fields) > 1 else ""
        if not _pid_alive(host_pid):
            stale_ids.append(fields[0])
    for container_id in stale_ids:
        _remove_container(container_id, debug=debug)


def build_image(
    dockerfile_path: Path,
    context_dir: Path,
    debug: bool = False,
) -> int:
    """Build the Docker image with a progressive status indicator.

    Arguments:
        dockerfile_path: Path to the project Dockerfile.
        context_dir: Docker build context directory. The Dockerfile contains
            no COPY instructions, so a minimal context (the .agent directory)
            keeps builds fast even for very large projects.
        debug: Whether to print the underlying Docker command to stderr.

    Returns:
        0 on success, otherwise the Docker build exit code.
    """
    log_handle = tempfile.NamedTemporaryFile(
        mode="w",
        prefix="ai-assistant-build-",
        suffix=".log",
        delete=False,
    )
    log_path = Path(log_handle.name)
    log_handle.close()

    try:
        command = [
            "docker",
            "build",
            "--progress=plain",
            "-t",
            AIDER_IMAGE,
            "-f",
            str(dockerfile_path),
            str(context_dir),
        ]
        _trace_command(command, debug)

        env = os.environ.copy()
        env["DOCKER_BUILDKIT"] = "1"

        with log_path.open("w") as log_file:
            try:
                process = subprocess.Popen(
                    command,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                    env=env,
                )
            except FileNotFoundError:
                print(
                    f"{ANSI_RED}Docker CLI not found while building image.{ANSI_RESET}",
                    file=sys.stderr,
                )
                return 127

            # Incremental log tail: read only newly appended bytes each tick
            # instead of re-reading and re-scanning the whole log file.
            spin_index = 0
            tail: deque[str] = deque(maxlen=40)
            reader = None
            try:
                reader = log_path.open("rb")
            except OSError:
                reader = None

            while process.poll() is None:
                if reader is not None:
                    chunk = reader.read()
                    if chunk:
                        tail.extend(
                            chunk.decode("utf-8", errors="replace").splitlines()
                        )

                status_message = ""
                if tail:
                    status_message = next(
                        (line for line in reversed(tail) if LOG_RE.search(line)),
                        "",
                    )[:45]
                if not status_message:
                    status_message = "Initializing build environment..."

                char = SPIN_CHARS[spin_index % len(SPIN_CHARS)]
                _print_spinner_update(char, status_message)

                spin_index += 1
                time.sleep(0.25)

            if reader is not None:
                reader.close()

            returncode = process.wait()

        if returncode != 0:
            if sys.stdout.isatty():
                sys.stdout.write(
                    f"\r[✖] Loading AI Assistant... failed.{' ':50}\n\n"
                )
                sys.stdout.flush()

            print(
                f"{ANSI_RED}--- Last lines of build log ---{ANSI_RESET}",
                file=sys.stderr,
            )
            for line in _tail_lines(log_path, 25):
                print(line, file=sys.stderr)
            print(
                f"{ANSI_RED}-----------------------------{ANSI_RESET}",
                file=sys.stderr,
            )
            return returncode

        # The fifty trailing spaces clear any remaining spinner text.
        if sys.stdout.isatty():
            sys.stdout.write(f"\r[✔] Loading AI Assistant... done.{' ':50}\n")
            sys.stdout.flush()
        return 0
    finally:
        try:
            log_path.unlink()
        except OSError:
            pass


def run_container(
    workspace_hash: str,
    session_id: str,
    container_name: str,
    docker_gid: Optional[int],
    agent_dir: Path,
    container_home: Optional[str],
    debug: bool,
    assistant_args: list[str],
) -> int:
    """Run the AI assistant Docker container.

    Arguments:
        workspace_hash: Docker label for the workspace.
        session_id: Docker label for the session.
        container_name: Name to assign to the Docker container.
        docker_gid: Host Docker group GID to add to the container, or None.
        agent_dir: Directory containing the AI assistant helper files.
        container_home: Passwd home of the container user, or None when
            unknown; the host ~/.ssh directory is additionally mounted
            under it so ssh finds the forwarded keys by default.
        debug: Whether to print the underlying Docker command to stderr.
        assistant_args: Additional arguments passed to the AI assistant.

    Returns:
        The exit code of the docker run process.
    """
    uid = os.getuid()
    gid = os.getgid()
    home = str(Path.home())
    cwd = os.getcwd()
    pulse_user_dir = f"/run/user/{uid}/pulse/native"

    command = [
        "docker",
        "run",
        "-it",
        "--rm",
        "--name",
        container_name,
        "--label",
        f"aider.dir={workspace_hash}",
        "--label",
        f"aider.session={session_id}",
        "--label",
        f"aider.hostpid={os.getpid()}",
        "--user",
        f"{uid}:{gid}",
    ]

    if docker_gid is not None:
        command.extend(["--group-add", str(docker_gid)])
    else:
        print(
            "Warning: host 'docker' group not found; skipping --group-add. "
            "Docker commands inside the container may fail with permission "
            "errors.",
            file=sys.stderr,
        )

    if Path("/dev/snd").exists():
        command.extend([
            "--group-add",
            "audio",
            "--device",
            "/dev/snd",
        ])

    # Docker-outside-of-Docker prerequisite: mounting a nonexistent socket
    # path makes the daemon create an empty directory in its place, which
    # silently breaks engine access inside the container.
    if not Path("/var/run/docker.sock").exists():
        print(
            "Warning: /var/run/docker.sock does not exist on the host; "
            "Docker commands inside the container will fail (e.g. when the "
            "host reaches its daemon through DOCKER_HOST).",
            file=sys.stderr,
        )

    command.extend([
        # Docker-outside-of-Docker: the CLI and compose plugin inside the
        # container drive the host daemon through this socket, so compose
        # stacks started for debugging are siblings, not nested containers.
        "-v",
        "/var/run/docker.sock:/var/run/docker.sock",
        # Same-path bind mount is load-bearing: it gives aider access to the
        # application source code AND makes host paths in compose files and
        # aider config arguments resolve identically inside the container.
        "-v",
        f"{cwd}:{cwd}",
        "-w",
        cwd,
        # Lets the assistant reach ports published on the host (e.g. by
        # sibling compose stacks) via http://host.docker.internal:<port>.
        "--add-host",
        "host.docker.internal:host-gateway",
    ])

    bashrc = Path(home) / ".bashrc"
    gitconfig = Path(home) / ".gitconfig"
    docker_config = Path(home) / ".docker"
    cache_dir = Path(home) / ".cache" / "aider"
    cache_dir.mkdir(parents=True, exist_ok=True)

    if bashrc.exists():
        command.extend(["-v", f"{bashrc}:/home/.bashrc:ro"])

    if gitconfig.exists():
        command.extend(["-v", f"{gitconfig}:/home/.gitconfig:ro"])

    # Mounted read-only so `docker compose` inside the container can use the
    # host's registry credentials when pulling or building images. Buildx's
    # mutable state is redirected off this mount via BUILDX_CONFIG below.
    if docker_config.exists():
        command.extend(["-v", f"{docker_config}:/home/.docker:ro"])

    # Mounted read-only so git push/pull over SSH remotes works inside the
    # container: keys, config, and known_hosts travel together, and the
    # container can never modify the host's SSH state. OpenSSH resolves
    # default identity and known_hosts paths from the passwd home
    # (pw_dir), not from $HOME, so when the image user's home differs
    # from /home the same directory is mounted there as well; otherwise
    # ssh never sees the keys (observed as "Permission denied
    # (publickey)" despite HOME=/home).
    ssh_dir = Path(home) / ".ssh"
    if ssh_dir.is_dir():
        command.extend(["-v", f"{ssh_dir}:/home/.ssh:ro"])
        if container_home and container_home != "/home":
            command.extend(["-v", f"{ssh_dir}:{container_home}/.ssh:ro"])

    # Agent-forwarded SSH: mount the host agent socket at its identical
    # path so passphrase-protected keys work without copying them (same
    # pattern as the pulse socket mount). The variable is forwarded after
    # --env-file below so a project .env cannot disarm the forwarding.
    ssh_auth_sock = os.environ.get("SSH_AUTH_SOCK")
    if ssh_auth_sock and Path(ssh_auth_sock).exists():
        command.extend([
            "-v",
            f"{ssh_auth_sock}:{ssh_auth_sock}",
        ])

    command.extend(["-v", f"{cache_dir}:/home/.cache"])

    if Path(pulse_user_dir).exists():
        command.extend([
            "-v",
            f"{pulse_user_dir}:{pulse_user_dir}",
            "-e",
            f"PULSE_SERVER=unix:{pulse_user_dir}",
        ])

    command.extend(["-v", "/dev/shm:/dev/shm"])

    tags_cache_dir = agent_dir / ".aider.tags.cache.v4"
    tags_cache_dir.mkdir(parents=True, exist_ok=True)
    command.extend([
        "-v",
        f"{tags_cache_dir}:{cwd}/.aider.tags.cache.v4",
    ])

    project_root = Path(cwd)
    env_file = project_root / ".env"
    agent_env_file = agent_dir / ".env"

    if env_file.exists():
        command.extend(["--env-file", str(env_file)])
    elif agent_env_file.exists():
        command.extend(["--env-file", str(agent_env_file)])

    # Environment forwards placed after --env-file so a project .env file
    # cannot override them (e.g. redirecting HOME or disarming SSH agent
    # forwarding). BUILDX_CONFIG: buildx keeps per-builder state under
    # $HOME/.docker/buildx, but /home/.docker is mounted read-only
    # (credentials only), which aborts in-container builds; point its
    # mutable state at the writable cache mount instead.
    command.extend([
        "-e",
        "HOME=/home",
        "-e",
        "PYTHONUNBUFFERED=1",
        "-e",
        "BUILDX_CONFIG=/home/.cache/buildx",
    ])
    if ssh_auth_sock and Path(ssh_auth_sock).exists():
        command.extend(["-e", "SSH_AUTH_SOCK"])

    # Forward host-exported credentials by name only: Docker fills the value
    # from this process's environment, so secrets never appear in the command
    # or its debug trace. Placed after --env-file so explicitly exported host
    # credentials take precedence over file defaults.
    for var in CREDENTIAL_ENV_VARS:
        if var in os.environ:
            command.extend(["-e", var])

    command.append(AIDER_IMAGE)
    command.extend(["--chat-mode", "ask"])

    # Detect project-root counterparts, then assemble config flags with
    # project-root merging applied (value files deep-merge; ignore patterns
    # union-merge).
    root_counterparts = _root_config_counterparts(Path(cwd))
    if root_counterparts and debug:
        print(
            "Project-root config counterparts detected: "
            + ", ".join(sorted(root_counterparts)),
            file=sys.stderr,
        )

    command.extend(_merged_config_args(agent_dir, root_counterparts, debug))

    # Keep aider metadata inside .agent rather than the project root. These
    # paths resolve inside the container because agent_dir sits under the
    # bind-mounted project root (enforced by _warn_agent_dir_location).
    command.extend([
        "--chat-history-file",
        str(agent_dir / ".aider.chat.history.md"),
        "--input-history-file",
        str(agent_dir / ".aider.input.history"),
    ])

    command.extend(assistant_args)

    _trace_command(command, debug)

    watchdog_pid = _start_container_watchdog(container_name, debug)
    try:
        try:
            return subprocess.run(command).returncode
        except FileNotFoundError:
            print(
                "Error: Docker CLI not found while starting assistant.",
                file=sys.stderr,
            )
            _dump_recent_log_lines(debug)
            return 127
        except KeyboardInterrupt:
            _remove_container(container_name, debug)
            return 130
    finally:
        _stop_watchdog(watchdog_pid)


def main() -> int:
    """Orchestrate the AI assistant launch."""
    assistant_args = sys.argv[1:]
    debug = False

    while assistant_args and assistant_args[0] in ("-x", "--debug"):
        debug = True
        assistant_args.pop(0)

    if os.name != "posix":
        print("This assistant currently supports Linux only.", file=sys.stderr)
        return 1

    # Configure the command log before the first engine command runs so the
    # Docker availability check is recorded too.
    project_root = Path.cwd()
    dir_name = project_root.name
    workspace_hash = hashlib.md5((str(project_root) + "\n").encode()).hexdigest()
    session_id = _resolve_session_id()
    command_log = _configure_command_log(workspace_hash, session_id)
    if debug:
        print(f"Command log: {command_log}", file=sys.stderr)

    if not _docker_available(debug=debug):
        print(
            "Docker CLI is not available. Please install Docker and ensure it is accessible from PATH.",
            file=sys.stderr,
        )
        _dump_recent_log_lines(debug)
        return 1

    # Pin GitHub's published SSH host keys on the host (fingerprint-
    # verified, append-only) so container git push/pull never stalls on a
    # host-key prompt; the pinned file travels into the container through
    # the read-only ~/.ssh mounts.
    if not _running_in_container():
        _ensure_github_known_hosts(debug=debug)

    container_name = (
        f"{TOOL_NAME}-{dir_name}-{workspace_hash[:8]}-{session_id}-{os.getpid()}"
    )
    docker_gid = _get_docker_gid()
    dockerfile_path = AGENT_DIR / "Dockerfile.aider"

    if not dockerfile_path.exists():
        print(
            f"Dockerfile.aider not found at {dockerfile_path}. Exiting.",
            file=sys.stderr,
        )
        return 1

    _warn_agent_dir_location(project_root)

    if _running_in_container():
        print(
            "Warning: the launcher appears to be running inside a container; "
            "skipping stale-container cleanup. The launcher must run on the "
            "host, where container aliveness can be checked reliably.",
            file=sys.stderr,
        )
    else:
        with _spinner("Checking for stale containers...", debug=debug):
            cleanup_containers(workspace_hash, debug=debug)

    # The Dockerfile performs no COPY, so the build context only needs the
    # Dockerfile itself. Using .agent (with its generated .dockerignore)
    # avoids shipping the whole repository to the daemon on every launch.
    _ensure_build_dockerignore(AGENT_DIR)

    with _spinner("Checking image cache...", debug=debug):
        cache_tag = _image_cache_tag(dockerfile_path, debug=debug)
        if debug:
            print(f"Image cache tag: {cache_tag}", file=sys.stderr)

        cache_hit = _image_exists(cache_tag, debug=debug)
        if cache_hit:
            command = ["docker", "tag", cache_tag, AIDER_IMAGE]
            _trace_command(command, debug)
            tag_result = subprocess.run(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            cache_hit = tag_result.returncode == 0

    if cache_hit:
        print(
            f"{ANSI_GREEN}[✔] Image up to date — skipping build ({cache_tag}).{ANSI_RESET}"
        )
        build_code = 0
    else:
        build_code = build_image(dockerfile_path, AGENT_DIR, debug=debug)
        if build_code == 0:
            command = ["docker", "tag", AIDER_IMAGE, cache_tag]
            _trace_command(command, debug)
            subprocess.run(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            # Once the base image is local its repo digests are known;
            # re-hash so the next run gets a stable, digest-aware tag.
            refreshed_tag = _image_cache_tag(dockerfile_path, debug=debug)
            if refreshed_tag != cache_tag:
                command = ["docker", "tag", AIDER_IMAGE, refreshed_tag]
                _trace_command(command, debug)
                subprocess.run(
                    command,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )

    if build_code != 0:
        return build_code

    aider_cache_dir = Path.home() / ".cache" / "aider"
    aider_cache_dir.mkdir(parents=True, exist_ok=True)

    # Discover the container user's passwd home (cached per image tag) so
    # the SSH keys are also mounted where ssh actually looks for them.
    container_home = None
    if not _running_in_container() and (Path.home() / ".ssh").is_dir():
        container_home = _container_passwd_home(cache_tag, debug=debug)

    result = run_container(
        workspace_hash,
        session_id,
        container_name,
        docker_gid,
        AGENT_DIR,
        container_home,
        debug,
        assistant_args,
    )

    _cleanup_empty_artifacts(project_root, AGENT_DIR)
    _remove_merged_intermediates(AGENT_DIR)

    return result


if __name__ == "__main__":
    sys.exit(main())
